### PR TITLE
Port Rob's tz-make-tiles branch to Python.

### PR DESCRIPTION
**Pull request by zerebubuth**
This sets up an "orchestration instance", which can be used to manage the tile build process from in the cloud. The idea is that this could be run from an automatic process, or with minimal human supervision.

### CODE REVIEW

**Comment by nvkelso** [comment]
“User data” is a trigger word, please use a more generic term.

**Comment by rmarianski** [comment]
> “User data” is a trigger word, please use a more generic term.

What's a trigger word? [User data](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html) is what AWS calls it.

**Comment by zerebubuth** [comment]
> “User data” is a trigger word, please use a more generic term.

Haha, it's a term of [AWS jargon](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html), but that probably doesn't help. Renamed to `provision` in 5a231c9.

**Comment by nvkelso** [comment]
Thanks!

**Pull request merged**
